### ISSUE TITLE
Document the build instructions please

### ISSUE THREAD

**Issue by doronbehar** [osmandapp/OsmAnd-tools#244]
I would like to distribute some of the tools in this repository as packages to the Arch Linux user repository. Specifically, I'd like to build the OsmAnd Creator butI don't have any experience with Java development tools and I don't know what [build.xml](https://github.com/osmandapp/OsmAnd-tools/blob/master/OsmAndMapCreator/build.xml) is used for.

Thanks.

**Comment by vshcherb** [comment]
The best documentation is the code. Lately there was a big refactoring that simplified project structure a lot. So for now there is only build.gradle https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreator/build.gradle

**Comment by doronbehar** [comment]
Hmm, I ran `gradle build --stacktrace` from the directory this file is found and I've received these errors: [gist](https://gist.github.com/doronbehar/88951b8bc6bda02900fc97c07e0bada5)

**Comment by vshcherb** [comment]
You need to use proper projects setup (repo checkout) - https://github.com/osmandapp/OsmAnd-manifest/blob/master/readonly.xml

**Comment by doronbehar** [comment]
As I said before, besides basic Gradle knowledge, I have no idea what to do with this [`readonly.xml` file](https://github.com/osmandapp/OsmAnd-manifest/blob/master/readonly.xml). Would you be kind enough to elaborate a little bit more? Thanks.

**Comment by doronbehar** [comment]
Should I open a new issue?

**Comment by frafra** [comment]
You should, or this issue should be reopened, in my opinion. Code is not documentation. Dockerfile does not build anything (it just copies existing artifacts), the repositories should be cloned mimicking the `readonly.xml` file (which I have no idea how to use directly without copy-and-pasting paths to `git clone`) and the released ZIP are quite different from what it is built (and there is no CI here, so no idea about how they are made).

It would be nice to have at least a brief paragraph to explain what is going on, if you are interested in having people making packages out of this repository and/or get some contributions, because this repository is handled in such a way that almost look like OSMAnd does not care at all, which I hope is not true. OSMAnd is a great software, and there is plenty of room to improve this repository and the cooperation with the community.
