### ISSUE TITLE
Missing OsmAndMapCreator.jar file

### ISSUE THREAD

**Issue by brad10281** [osmandapp/OsmAnd-tools#858]
I downloaded the latest version of OsmAndMapCreator and found that it's missing the OsmAndMapCreator.jar file.

**Comment by brad10281** [comment]
Are you using Windows? I find that if you unzip it using Linux, it works fine and the file is there. Maybe try 7-Zip on Windows. I don't know why the file isn't there when you unzip in Windows.

**Comment by josail** [comment]
Thanks for your hint. 

Yes, with 7-zip I find it, still difficult, because it is hidden in  a subfolder named "." but if I manually unzip it from this subfolder in 7-zip to the top/main folder level with the .bat files in win11, the .bat file can find it and it works. 
This is not intuitive and should best come with more instruction for win users.
